### ISSUE TITLE
Repository peer review

### ISSUE THREAD

**Issue by cnhguy** [s92025592025/checkstyle-idea#31]
(1/4 pts) You can follow the instructions to reproduce the results in the paper. 
The instructions in week10/report.pdf say to use Python 3 but I found that generate_figures.sh actually uses Python 2.7. Attempting to run the original with python 2.7 and changing the command to use python 3 yielded the same error: i.e. that jpg files are not supported.
```
Traceback (most recent call last):
  File "./reports/week10/evaluation/generate_figures.py", line 209, in <module>
    main()
  File "./reports/week10/evaluation/generate_figures.py", line 146, in main
    plot_time_to_complete(time_to_complete_dict(ttc), path.join(directory, 'figures'))
  File "./reports/week10/evaluation/generate_figures.py", line 71, in plot_time_to_complete
    plt.savefig(path.join(out_dir, 'average_completion_time.jpg'))
  File "/home/eric/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 695, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/eric/.local/lib/python2.7/site-packages/matplotlib/figure.py", line 2062, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/eric/.local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2173, in print_figure
    canvas = self._get_output_canvas(format)
  File "/home/eric/.local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2105, in _get_output_canvas
    .format(fmt, ", ".join(sorted(self.get_supported_filetypes()))))
ValueError: Format 'jpg' is not supported (supported formats: eps, pdf, pgf, png, ps, raw, rgba, svg, svgz)
```
After changing all occurrences of jpg to png, the figures were reproduced on both python 2.7 and python 3, except for average_completion_time which appears to be different from the one present in the report:
![average_completion_time](https://user-images.githubusercontent.com/30064998/54401946-3548bf00-4687-11e9-9ce7-b5adbecbcd23.png)

(2/2 pts) These instructions are fully automated. 
Besides the jpg error, the script does produce the results automatically. No further input is needed.

(4/4 pts) The code and experimental results are well documented. 
All of the code appears to be well documented with ample javadoc style comments for methods and classes as well as comments for fields and within methods, when necessary. The experiments are well documented and it is clear who the participants are and what questions/tasks were used. The analysis of the results is also good: there are many graphs to clearly show the results, and the discussion focuses on both the supporting and opposing evidence and draws conclusions from the results appropriately, as well as mentioning future improvements based on the results.

**Comment by OfekI** [comment]
My mistake on the shell script, I incorrectly assumed that the command to run `Python 3` was the same on Windows and Unix!
In order for the `jpg` export to work without error, with some research I discovered `matplotlib` has an additional package dependency on `PIL`, so running `pip install pillow` or `pip3 install pillow` should do the trick.

I am not sure why the figure you got for `average_completion_time.jpg` is different than the one we have in the report, but it appears to have missed some of the data...
